version: '3'
services: 
  echo:
    container_name: "echo"
    build: 
      context: .
    restart: always
    network_mode: bridge 
    environment: 
      PORT: 8200
      HOST: 0.0.0.0
      MAX_CONNECTIONS: 200
    ports: 
      - "8200:8200"